version: "1.0"
services:
  mysql:

    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password    
    ports:
      - 3306:3306

    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: festmaker

      MYSQL_USER: root